// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5izdHFLHGFzkNjRI_UkdCCuzuUnaaAM',
    appId: '1:396440535539:web:919ae177e104640a109286',
    messagingSenderId: '396440535539',
    projectId: 'daycareapp-2b3b0',
    authDomain: 'daycareapp-2b3b0.firebaseapp.com',
    storageBucket: 'daycareapp-2b3b0.firebasestorage.app',
    measurementId: 'G-79Y0XQF9R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpk0zOj3FqdFGAVLUqStO0nQ2PUsLkbU',
    appId: '1:396440535539:android:78db3ef2209d5283109286',
    messagingSenderId: '396440535539',
    projectId: 'daycareapp-2b3b0',
    storageBucket: 'daycareapp-2b3b0.firebasestorage.app',
  );
}
